host:
port: 9531 # This is tge standard port for the exporter
api_key: 
https: true
ignore_ssl: false
# Can be set to `admin-all` (return all servers), `owner` (only owned servers)
# or "" (only accessible servers, shown in your servers list)
server_list_type: owner
