version: "3"
services:
  pterodactyl-exporter:
    image: noesterle/pterodactyl_exporter:latest
    container_name: pterodactyl-exporter
    ports:
      - "9531:9531"
    volumes:
      - ../config.yml:/opt/pterodactyl_exporter/config/config.yml
